ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shops.urls', namespace='shops'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

shops/urls.py
from django.urls import path

from .views import (
	products,
	OrderSummaryView,
	CheckoutView,
	# HomeView,
	home,
	about,
	services,
	contact,
	Newproduct,
	post_create,
	add_to_cart,
	remove_from_cart,
	remove_single_item_from_cart,
	PaymentViews,
	Mpesa,
	AddCouponView,
	RequestRefundView,
	list_category,
	callbackurl,
	getOrder,
	
)

app_name = 'shops'
	
urlpatterns = [
	# path('', HomeView.as_view(), name='home'),
	path('', home, name='home'),
	path('about/', about, name='about'),
	path('contact', contact, name='contact'),
	path('new/', Newproduct, name='new'),
	path('services', services, name='services'),
	path('callbackurl', callbackurl, name='callbackurl'),
	path('create/', post_create, name='create'),
	path('category/<int:id>/', list_category, name='list_category'),
	path('product/<int:id>/', products, name='product'),
	path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
	path('checkout/', CheckoutView.as_view(), name='checkout'),
	path('add-to-cart/<int:id>/', add_to_cart, name='add-to-cart'),
	path('remove-from-cart/<int:id>/', remove_from_cart, name='remove-from-cart'),
	path('remove-item-from-cart/<int:id>/', remove_single_item_from_cart,
						 name='remove-single-item-from-cart'),
	path('payment/<payment_option>/', PaymentViews.as_view(), name='payment'),
	path('mpesapay/<payment_option>/', Mpesa.as_view(), name='mpesapay'),
	path('add-coupan/', AddCouponView.as_view(), name='add-coupan'),
	path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
	path('orders/', getOrder, name='orders'),
]

shops/models.py
from django import forms
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.

# def upload_location(instance, filename):
# 	return "%s/%s" %(instance.id, filename)

class Category(models.Model):
	name = models.CharField(max_length=250)
	

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_category_absolete_url(self):
		return reverse('shops:list_category', args=[self.id])

	def __str__(self):
		return self.name
		

CATEGORY_CHOICES = (
	('S',  'Shirts'),
	('SW', 'Sport weare'),
	('OW', 'Outwear')
)

LABEL_CHOICES = (
	('P', 'primary'),
	('S', 'secondary'),
	('D', 'danger')
)

ADDRESS_CHOICES = (
	('B', 'Billing'),
	('S', 'Shipping')
)

class Item(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE,
                    related_name="category_set")
	title = models.CharField(max_length=100)
	price = models.FloatField()
	discount_price = models.FloatField(blank=True, null=True)
	# category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
	size = models.CharField(max_length=100)
	color = models.CharField(max_length=100)
	type_cloth  = models.CharField(max_length=100)
	label = models.CharField(choices=LABEL_CHOICES, max_length=1)
	image = models.ImageField(
					null=True, 
					blank=True,
					width_field="width_field",
					height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field  = models.IntegerField(default=0)
	description = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __str__(self):
		return self.title

	def get_absolete_url(self):
		return reverse("shops:product", kwargs={
				'id': self.id
			})

	def get_add_to_cart_url(self):
		return reverse("shops:add-to-cart", kwargs={
			'id': self.id
			})

	def get_remove_from_cart_url(self):
		return reverse("shops:remove-from-cart", kwargs={
			'id':self.id
			})

class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
													on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	ordered = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __str__(self):
		return "%s %s" %(self.quantity, self.item.title)
	
	# Total quantity price
	def get_total_item_price(self):
		return self.quantity * self.item.price

	# Discount on Items
	def get_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_discount_item_price()

	# Function return the final total price
	def get_final_price(self):
		if self.item.discount_price:
			return self.get_discount_item_price()
		return self.get_total_item_price()


class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
													on_delete=models.CASCADE)
	ref_code = models.CharField(max_length=20)
	items = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField(auto_now=False, auto_now_add=True)
	ordered = models.BooleanField(default=False)
	billing_address = models.ForeignKey(
		'BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
	payment = models.ForeignKey(
		'Payment', on_delete=models.SET_NULL, blank=True, null=True)
	mpesa_pay = models.ForeignKey(
		'Mpesapay', on_delete=models.SET_NULL, blank=True, null=True)
	coupon = models.ForeignKey(
		'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
	being_delivered = models.BooleanField(default=False)
	received_requested = models.BooleanField(default=False)
	refund_requested = models.BooleanField(default=False)
	refund_granted = models.BooleanField(default=False)

	'''
	1. Item added to cart
	2. Adding a billing address
	(Failed checkout)
	3. payment
		(Preprocessing, processing, packing, etc)
	4. Being delivered
	5. Received
	6. Refunds
	'''

	def __str__(self):
		return self.user.username

	# Function get the final tatol 
	def get_total(self):
		total = 0
		for order_item in self.items.all():
			total += order_item.get_final_price()
		if self.coupon:
			total -= self.coupon.amount
		return total

class BillingAddress(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
														on_delete=models.CASCADE)
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	phone = models.BigIntegerField(blank=True, null=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __str__(self):
		return self.user.username

class Payment(models.Model):
	stripe_change_id = models.CharField(max_length=50)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
													on_delete=models.SET_NULL, blank=True, null=True)
	amount = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__self(self):
		return self.user.username

		
class Mpesapay(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
													on_delete=models.SET_NULL, blank=True, null=True)
	amount = models.FloatField()
	phone = models.BigIntegerField(blank=True, null=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	cash = models.CharField(default='notpayed', max_length=15)

	def __str__(self):
		return self.user.username


class Coupon(models.Model):
	code = models.CharField(max_length=15)
	amount = models.FloatField()

	def __str__(self):
		return self.code 

class Refund(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	reason = models.TextField()
	accepted = models.BooleanField(default=False)
	email = models.EmailField(max_length=100)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __str__(self):
		return "%s" %(self.pk)

# Image 
class Images(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE,)
	image = models.ImageField(
		null=True,
		blank=True)

	def __str__(self):
		return self.post.title + "Image"

class Contact(models.Model):
	full_name = models.CharField(max_length=120)
	phone  = models.IntegerField()
	email = models.CharField(max_length=150)
	subject = models.CharField(max_length=200)
	message = models.TextField(max_length=500)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.full_name

	def __str__(self):
		return self.full_name


		

templates/base.html
{% load staticfiles %}

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
	  <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/stylecomm.css' %}"/>
  

{% include "nav3.html" %}

<div class="mt-5 pt-4">{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role ="alert">
    {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endfor %}
  {% endif %}
</div>

{% block content %}{% endblock content %}

{% block extra_body %}
{% endblock %}
  

{% include "footer.html" %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/category.html
{% extends "base.html" %}


{% block content %}

<div class="category">
	<h1 class="text-center">
		<span>{{ category.name }}</span> Categories
	</h1>
</div>
<div class="container-fluid">
  <div class="row wow fadeIn"> 
	{% for items in item %}
<div class="col-lg-2 col-md-6 mt-4 mb-4">
<div class="card">
 <div class="view overlay">
  <div class="image">
  <img src="{{ items.image.url }}" class="card-img-top" alt=""> 
    <a href="{{ items.get_absolete_url }}">
  
    <div class="mask rgba-white-slight"></div>
  </a>
    <div class="card-body text-center">

<strong>

  <a href="{{ items.get_absolete_url }}" class="dark-grey-text" style="font-weight: bold; font-size: 20px;">{{ items.title }}</a> &nbsp;&nbsp;&nbsp;
<a href="{{ items.category.get_category_absolete_url }}" class="badge badge-pill {{ items.get_label_display }}-color">{{ items.category }}</a>
</strong></h5>
 <h5 class="font-weight-bold blue-text">
   <strong>
  {% if items.discount_price %}
  {{ items.discount_price }}
  {% else %}

    Ksh {{ items.price }}
  {% endif %} </strong>
</h5>
</div>
  </div>
  </div>
  </div>
	</div>
		{% endfor %}

	</div>
</div>


{% endblock content %} 

templates/home.html
{% extends "base.html" %}

{% block content %}

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="../static/wer.jpg"
        alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="../static/dx1.jpg"
        alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="../static/dx1.jpg"
        alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<!-- All Products -->
<div class="container-fluid">
<div class="allclass">
{% for links in link %}
<h5><a href="#" style="color: #4B515D !important; font-weight: bold; 
font-size: 18px;">
<span style="color: #FF8800;">All New Ralated Products</span>| <span>See all -->{{ cat.price }}</span></a></span></h5>
{% endfor %}

<br/>
  <div class="row wow fadeIn"> 
  <!--Fourth column-->
  {% for item in object_list %}
<div class="col-lg-2 col-md-6 mb-4">
<div class="card">
 <div class="view overlay">
  <div class="image">
  <img src="{{ item.image.url }}" class="card-img-top" alt=""> 
    <a href="{{ item.get_absolete_url }}">
  
    <div class="mask rgba-white-slight"></div>
  </a>
  </div>
  </div>
  <div class="card-body text-center">
  <!--Category & Title-->
  <a href="{{ item.category.get_category_absolete_url }}" class="grey-text">
  </a>
<h5>
<strong>
  <a href="{{ item.get_absolete_url }}" class="dark-grey-text" style="font-size: 16px;">{{ item.title }}</a> &nbsp;&nbsp;&nbsp;

  <a href="{{ item.category.get_category_absolete_url }}" class="badge badge-pill {{ item.get_label_display }}-color">{{ item.category }}</a>
</strong></h5>
 <h5 class="font-weight-bold blue-text" style="font-size: 18px; font-weight: bold;">
   
  {% if item.discount_price %}
  {{ item.discount_price }}
  {% else %}

    Ksh {{ item.price }}
  {% endif %} 
</h5>
</div>
<!--Card content-->

  </div>
  <!--Card-->
</div>
<!--Fourth column-->
{% endfor %}
</div>
<!--Grid row-->

</section>
<!--Section: Products v.3-->
    </div>
</div>

{% include "card.html" %}

<br/>

<!-- -Trouser collections -->
<div class="container-fluid">
<div class="trouser">

<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

  <div class="row">
<div class="col-md-3">
{% for links in link %}
<h5><a href="{{ links.category.get_category_absolete_url }}" style="color: #4B515D !important; font-weight: bold; 
font-size: 18px;">
Best <span style="color: #FF8800;">Trousers</span>| <span>See all -->{{ cat.price }}</span></a></span></h5>
{% endfor %}
</div>

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
    <li data-target="#multi-item-example" data-slide-to="1"></li>
    <li data-target="#multi-item-example" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
  <div class="row">
    {% for category in cat %}

      <div class="col-md-2">
        <div class="card mb-2">
       <div class="view overlay">
          <div class="image">
          <img src="{{ category.image.url }}" class="card-img-top" alt=""> 
            <a href="{{ category.get_absolete_url }}">
          
            <div class="mask rgba-white-slight"></div>
          </a>
          </div>
          <h6 style="padding-left: 10px; padding-top: 5px; font-weight: bold;">Ksh {{ category.price }}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <!--/.Third slide-->
  </div>
  <!--/.Slides-->

</div>
</div>
</div>
</div></div>

<br/>

<!-- Shoes Collections -->
<div class="container-fluid">
<div class="trouser">

<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

  <div class="row">
<div class="col-md-3">
{% for links in linkshoes %}
<h5><a href="{{ links.category.get_category_absolete_url }}" style="color: #444 !important; font-weight: bold; 
font-size: 18px;">
Best <span style="color: #FF8800;">Shoes</span> | <span>See all --></span></a></span></h5>
{% endfor %}
</div>

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
    <li data-target="#multi-item-example" data-slide-to="1"></li>
    <li data-target="#multi-item-example" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
  <div class="row">
    {% for category in shoes_cat %}

      <div class="col-md-2">
        <div class="card mb-2">
       <div class="view overlay">
          <div class="image">
          <img src="{{ category.image.url }}" class="card-img-top" alt=""> 
            <a href="{{ category.get_absolete_url }}">
          
            <div class="mask rgba-white-slight"></div>
          </a>
          </div>
          <h6 style="padding-left: 10px; padding-top: 5px; font-weight: bold;">Ksh {{ category.price }}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <!--/.Third slide-->
  </div>
  <!--/.Slides-->

</div>
</div>
</div>
</div>
</div>

<br/>

<!--Tops Collections-->
<div class="container-fluid">
<div class="trouser">

<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

  <div class="row">
<div class="col-md-3">
{% for tops in tops_cat_link %}
<h5><a href="{{ tops.category.get_category_absolete_url }}" style="color: #444 !important; font-weight: bold; 
font-size: 18px;">
Best <span style="color: #FF8800;">Tops</span> | <span>See all --></span></a></span></h5>
{% endfor %}
</div>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
    <li data-target="#multi-item-example" data-slide-to="1"></li>
    <li data-target="#multi-item-example" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
  <div class="row">
    {% for category in tops_cat %}

      <div class="col-md-2">
        <div class="card mb-2">
       <div class="view overlay">
          <div class="image">
          <img src="{{ category.image.url }}" class="card-img-top" alt=""> 
            <a href="{{ category.get_absolete_url }}">
          
            <div class="mask rgba-white-slight"></div>
          </a>
          </div>
          <h6 style="padding-left: 10px; padding-top: 5px; font-weight: bold;">Ksh {{ category.price }}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <!--/.Third slide-->
  </div>
  <!--/.Slides-->

</div>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/nav.html
 <div> <!-- Padding Youc can remove or addjust accourding to the shadow of the navbar -->
<nav class="navbar navbar-expand-lg custom-navbar navbar-light fixed-top" id="main_navbar">
        <a class="navbar-brand logo" href="#">
    <img src="../static/logo.jpg" alt="logo" style="width:130px; height: 60px;">
    </a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a class="nav-link" href="#" style="color: #fff; font-size: 20px; font-weight: bold;"><i class="fa fa-home"> </i>Home</a>
    </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
   <form id="custom-search-form" class="form-search form-horizontal pull-right">
    <div class="input-append span12">
    <input type="text" class="search-query" placeholder="Search">
        <button type="submit" class="btn"><i class="fas fa-search"></i></button>
            </div>
    </form>
    </div>
  <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'shops:order-summary' %}" class="nav-link waves-effect" style="color: #fff; font-size: 20px; font-weight: bold;">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}" style="color: #fff; font-size: 20px; font-weight: bold;">             
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>

          {% else %}
          
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}" style="color: #fff; font-size: 20px; font-weight: bold;">             
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}" style="color: #fff; font-size: 20px; font-weight: bold;">             
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
        </li>
          {% endif %}
        </ul>
</div>
 </nav>
</div>

templates/new.html
{% extends "base.html" %}


{% block content %}

<div class="container-fluid">
<div class="row wow fadeIn"> 
  <!--Fourth column-->
  {% for item in newproduct %}
<div class="col-lg-2 col-md-6 mb-4">
<div class="card">
 <div class="view overlay">
  <div class="image">
  <img src="{{ item.image.url }}" class="card-img-top" alt=""> 
    <a href="{{ item.get_absolete_url }}">
  
    <div class="mask rgba-white-slight"></div>
  </a>
  </div>
  </div>
  <div class="card-body text-center">
  <!--Category & Title-->
  <a href="{{ item.category.get_category_absolete_url }}" class="grey-text">
  </a>
<h5>
<strong>
  <a href="{{ item.get_absolete_url }}" class="dark-grey-text">{{ item.title }}</a> &nbsp;&nbsp;&nbsp;

  <a href="{{ item.category.get_category_absolete_url }}" class="badge badge-pill {{ item.get_label_display }}-color">{{ item.category }}</a>
</strong></h5>
 <h5 class="font-weight-bold blue-text" style="font-size: 18px; font-weight: bold;">
   
  {% if item.discount_price %}
  {{ item.discount_price }}
  {% else %}

    Ksh {{ item.price }}
  {% endif %} 
</h5>
</div>
<!--Card content-->

  </div>
  <!--Card-->
</div>
<!--Fourth column-->
{% endfor %}
</div>
<!--Grid row-->

</section>
<!--Section: Products v.3-->
    </div>
</div>
<section class="padd z-depth-1" style="background-color: #fff; padding: 1em;">
<div class="container">
  <div class="row">
   <div class="col">
  <h1 class="card-title" style="color: #4B515D
; font-size: 2em;"> Find More Properties</h1>
  </div>

<div class="col-12 col-md-auto">
  <div class="pagination" style="font-size: 1.5em; font-weight: 500; color: #4B515D;">
    <span class="step-links">
        {% if newproduct.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ newproduct.previous_page_number }} {% if request.GET.q %} &q={{ request.GET.q }} {% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ newproduct.number }} of {{ newproduct.paginator.num_pages }}.
        </span>

        {% if newproduct.has_next %}
            <a href="?page={{ newproduct.next_page_number }}">next</a>
            <a href="?page={{ newproduct.paginator.num_pages }} {% if request.GET.q %} &q={{ request.GET.q }} {% endif %}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>

</div>
</div>
</section>


{% endblock content %}

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
	<main>
	<div class="category">
	<h1 class="text-center">
		<h2>Order Summary</h2>
	</h1>
	<br><br>
		<div class="container">
			<div class="table-responsive text-nawrap">
			<table class="table">
					<thead>
						<tr>
						<th scope="col">#</th>
						<th scope="col">Item title</th>
						<th scope="col">Price</th>
						<th scope="col">Quantity</th>
						<th scope="col">Total Item Price</th>
						</tr>
					</thead>
					<tbody>

					{% for order_item in object.items.all %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>{{ order_item.item.title }}</td>
						<td>{{ order_item.item.price }}</td>
						<td>
							<a href="{% url 'shops:remove-single-item-from-cart' order_item.item.id %}"><i class="fas fa-minus mr-2"></i></a>
								{{ order_item.quantity }}
							<a href="{% url 'shops:add-to-cart' order_item.item.id %}"><i class="fas fa-plus ml-2"></i></a>
						</td>
						<td>
						{% if order_item.item.discount_price %}
								{{ order_item.get_discount_item_price }}
								<span class="badge badge-primary">Saving KSH{{ order_item.get_amount_saved }}</span>
						{% else %}
								{{ order_item.get_total_item_price }}
						{% endif %}

						<a style="color:red;" href="{% url 'shops:remove-from-cart' order_item.item.id %}"><i class="far fa-trash-alt float-right"></i>
						</td>
						</td>
						</tr>

					{% empty %}
						<tr>
							<td colspan="5">Your Cart is empty</td>
						</tr>
						<tr>
							<td colspan="5">
							<a class="btn btn-primary float-right" href="/">Continue shopping</a>
							</td>
						</tr>
						{% endfor %}

						<tr>
						{% if object.coupon %}
							<td colspan="4"><b>Coupon</b></td>
							<td><b> - {{ object.coupon.amount }}</b></td>
						</tr>
						{% endif %}

						<tr>
						{% if object.get_total %}
							<td colspan="4"><b>Order Total</b></td>
							<td><b> {{ object.get_total }} KSH</b></td>
						</tr>

						<tr>
							<td colspan="5">
								<a class='btn btn-warning float-right ml-2' href="/checkout/">Proceed to checkout</a>

								<a class='btn btn-primary float-right' href="/">Continue Shopping</a>
							</td>
						</tr>
						{% endif %}
					</tbody>
					
				</table>
			</div>

		</div>
	</main>
{% endblock content %}